version: '3'
services:

  eu-01:
    image: quay.io/infinispan/server:15.0
    privileged: true
    network_mode: host
    volumes:
      - ./conf/infinispan-europe.yaml:/opt/infinispan/server/conf/infinispan-europe.yaml:Z
      - ./conf/infinispan-openldap.yaml:/opt/infinispan/server/conf/infinispan-openldap.yaml:Z
      - ./conf/log4j2.xml:/opt/infinispan/server/conf/log4j2.xml:Z
    environment:
      USER: admin
      PASS: password
      ISPN_HOME: /opt/infinispan
      JAVA_OPTIONS: "-Dinfinispan.node.name=infinispan-europe-01"
    ports:
      - 11222:11222
    # networks:
    #   - infinispan
    depends_on:
      - openldap
    command:
      - "-c infinispan.xml"
      - "-c infinispan-europe.yaml"
      - "-c infinispan-openldap.yaml"

  openldap:
    image: docker.io/bitnami/openldap:2.6.6
    container_name: openldap
    # privileged: true
    network_mode: host
    ports:
      - 1389:1389 # LDAP  connections
      - 1636:1636 # LDAPS connections
    environment:
      LDAP_ROOT: dc=acme,dc=org
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_CUSTOM_LDIF_DIR: /tmp/ldifs
      # BITNAMI_DEBUG: true
    volumes:
      - ./ldifs:/tmp/ldifs:Z

# networks:
#   infinispan:
#     driver: bridge
