apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana-deployment
  annotations:
    description: Template to deploy a Grafana deployment on OCP.
    tags: grafana,community,operator
    iconClass: icon-cassandra
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: grafana-proxy
    namespace: ${OPERATOR_NAMESPACE}
  data:
    session_secret: Y2hhbmdlIG1lCg==
  type: Opaque
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      config.openshift.io/inject-trusted-cabundle: "true"
    name: ocp-injected-certs
    namespace: ${OPERATOR_NAMESPACE}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: grafana-serviceaccount
    namespace: ${OPERATOR_NAMESPACE}
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: grafana-proxy
    namespace: ${OPERATOR_NAMESPACE}
  rules:
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: grafana-proxy
    namespace: ${OPERATOR_NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: grafana-proxy
  subjects:
    - kind: ServiceAccount
      name: grafana-serviceaccount
      namespace: ${OPERATOR_NAMESPACE}
  userNames:
    - "system:serviceaccount:${OPERATOR_NAMESPACE}:grafana-serviceaccount"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: grafana-cluster-monitoring-binding
    namespace: ${OPERATOR_NAMESPACE}
  subjects:
    - kind: ServiceAccount
      namespace: ${OPERATOR_NAMESPACE}
      name: grafana-serviceaccount
  roleRef:
    kind: ClusterRole
    name: cluster-monitoring-view
    apiGroup: rbac.authorization.k8s.io
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: grafana-access
    namespace: ${OPERATOR_NAMESPACE}
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
    labels:
      app: grafana
  spec:
    port:
      targetPort: grafana
    # tls:
    #   termination: edge
    to:
      kind: Service
      name: grafana-service
      weight: 100
    wildcardPolicy: None
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "grafana"