apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-caches
  annotations:
    description: Template to configure caches inside a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-01
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-01
    template: >-
      <distributed-cache name="doesnotapply" owners="1" mode="ASYNC" statistics="true">
        <encoding media-type="application/x-protostream"/>
        <state-transfer enabled="false"/>
        <memory max-size="400MB" when-full="REMOVE"/>
        <expiration lifespan="600000"/> <!-- 10 min -->
      </distributed-cache>
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-02
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-02
    template: |-
      distributedCache:
        owners: "1"
        mode: SYNC
        statistics: "true"
        encoding:
          key:
            mediaType: application/x-protostream
          value:
            mediaType: application/x-protostream
        expiration:
          lifespan: "4000"
          maxIdle: "-1"
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: ${CLUSTER_NAME}-operator-cache-03
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    clusterName: ${CLUSTER_NAME}
    name:  operator-cache-03
    templateName: proto-dist-template
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "rhdg8"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "rhdg"