apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-monitoring
  annotations:
    description: Template to configure the monitoring stack for a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: infinispan-operator-config
  #     namespace: ${OPERATOR_NAMESPACE}
  #   data:
  #     grafana.dashboard.namespace: ${CLUSTER_NAMESPACE}
  #     grafana.dashboard.name: infinispan-dashboard
  #     grafana.dashboard.monitoring.key: middleware
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      # Avoid using ${CLUSTER_NAME}-monitor. The operator will automatically remove it.
      name: ${CLUSTER_NAME}-service-monitor
      namespace: ${CLUSTER_NAMESPACE}
    spec:
      # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint
      endpoints:
      - basicAuth:
          password:
            key: password
            name: ${CLUSTER_NAME}-generated-operator-secret
          username:
            key: username
            name: ${CLUSTER_NAME}-generated-operator-secret
        bearerTokenSecret:
          key: ""
        honorLabels: true
        interval: 30s
        path: /metrics
        port: infinispan-adm
        # Option 2 to inherit all labels from service 
        # relabelings:
        #   - action: labelmap
        #     regex: __meta_kubernetes_service_label_(.+)
        # Option 3 to inherit all labels starting on prometheus_ from service. The final metric does not contain prometheus_
        # relabelings:
        #   - action: labelmap
        #     regex: __meta_kubernetes_service_label_prometheus_(.+)
            # regex: __meta_kubernetes_pod_label_prometheus_(.+)
        scheme: ${SERVICE_MONITOR_HTTP_SCHEME}
        scrapeTimeout: 10s
      namespaceSelector:
        matchNames:
        - ${CLUSTER_NAMESPACE}
      # Option 1 to inherit specific labels from service
      targetLabels:
        - domain
      selector:
        matchLabels:
          app: infinispan-service-admin
          clusterName: ${CLUSTER_NAME}
          infinispan_cr: ${CLUSTER_NAME}
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "rhdg8"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "rhdg"
- name: SERVICE_MONITOR_HTTP_SCHEME
  description: "The scheme to connect to metrics."
  required: false
  value: "http"
# - name: GRAFANA_NAMESPACE
#   description: "The project where the Grafana will be installed."
#   required: true
#   value: "grafana"
# - name: OPERATOR_NAMESPACE
#   description: "The project where the Grafana will be installed."
#   required: true
#   value: "rhdg8-operator"
