apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cert-manager-operator
  annotations:
    description: Template to deploy a Cert-Manager operator on OCP.
    tags: cert-manager,community,operator
    iconClass: icon-cassandra
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of Cert-Manager"
      openshift.io/display-name: "Cert-Manager - Operator"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: cert-manager-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${OPERATOR_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: cert-manager-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: stable-v1.11
    installPlanApproval: Automatic
    name: openshift-cert-manager-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "cert-manager-operator"